### ISSUE TITLE
紧急！上传失败：apply upload failed

### ISSUE THREAD

**Issue by haoyinag** [tencentyun/vod-js-sdk-v6#1]
代码：
  import axios from 'axios';
  import TcVod from 'vod-js-sdk-v6'

created() {
      function getSignature() {
        return axios.get('http://192.168.1.166/api/external/v1/VOD/uploadSignature').then(function(response) {
          // console.log(response.data);
          return response.data.data
        })
      }
      this.tcVod = new TcVod({
        getSignature: getSignature
      })
      console.log(this.tcVod);
    },
    methods: {
      onUpload(e) {
        const file = e.target.files[0]
        const uploader = this.tcVod.upload({
          videoFile: file // 视频，类型为 File
        })
        console.log(uploader); // 输出成功
        uploader.on('video_upload', function(info) {
          // uploaderInfo.isVideoUploadSuccess = true;
          console.log(info);
        })
        console.log(uploader, 'uploader')
      }
    }

之后就报错：apply upload failed

**Comment by liwen327** [comment]
我这里也有同样的错误。

**Comment by liwen327** [comment]
@haoyinag 你解决这个问题了吗？

**Comment by haoyinag** [comment]
没，文档太简陋了，错误钩子也没给，clone下拉项目也没法运行

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: liwen327 <notifications@github.com>
发送时间: Tuesday, March 19, 2019 5:41:19 PM
收件人: tencentyun/vod-js-sdk-v6
抄送: ChenHaoYin; Mention
主题: Re: [tencentyun/vod-js-sdk-v6] 紧急！上传失败：apply upload failed (#1)


@haoyinag<https://github.com/haoyinag> 你解决这个问题了吗？

―

**Comment by haoyinag** [comment]
@liwen327 可以了，文档的坑；是后台接口请求少了参数，具体少的参数让后台去验证

**Comment by haoyinag** [comment]
@liwen327 @zhongfox @puterjam @yaozongyou 
VUE的上传成功了，但是angular还是上传失败，报相同的错误
一模一样的代码
调试的时候很奇怪，猜测是明明能获取到videoinfo等信息，最后还是获取不到，以致报错
能否有给个回答？

**Comment by 18883278826** [comment]
> @liwen327 @zhongfox @puterjam @yaozongyou
> VUE的上传成功了，但是angular还是上传失败，报相同的错误
> 一模一样的代码
> 调试的时候很奇怪，猜测是明明能获取到videoinfo等信息，最后还是获取不到，以致报错
> 能否有给个回答？
我用下下来的demo调我们后台接口是可以的，但是那个demo是script标签应用的sdk，我放到vue项目中就不行了，亲，能看下你的那段代码么

**Comment by alsotang** [comment]
常见故障排查 https://github.com/tencentyun/vod-js-sdk-v6/wiki/%E5%B8%B8%E8%A7%81%E6%95%85%E9%9A%9C%E6%8E%92%E6%9F%A5

**Comment by HDanube** [comment]
> @ liwen327 @zhongfox @puterjam @yaozongyou
> VUE的上传成功了，但是angular还是上传失败，报相同的错误
> 一模一样的代码
> 调试的时候很奇怪，可能是明明能获取到videoinfo等信息，最后还是获取不到，以致报错
> 能否有给个回答？

请问解决了吗？ angular 的写法是怎么样的呢？ 我也引用了这个插件 但是angular 我不会初始化
