### ISSUE TITLE
Transcode

### ISSUE THREAD

**Issue by 960269073** [tencentyun/vod-js-sdk-v6#2]
老版本的api提供了isTranscode参数，可以在上传完成后自动开始转码，在这一版的api没有提供类似参数？

**Comment by alsotang** [comment]
我以为现在是上传后默认自动转码的。请问现在的行为是如何的？

**Comment by 960269073** [comment]
事实上上传完毕并不会自动开始转码，我已通过修改GetSignature签发的Signature实现上传完毕立即转码。建议您提供类似参数方便指定是否上传完毕自动开始转码

**Comment by alsotang** [comment]
我跟后端确认一下。我接手这 sdk 的时候没遇到过 isTranscode 这个参数。

**Comment by alsotang** [comment]
这是后端给我的答复

> 有这个参数，但是要废弃，全部通过签名的Procedure触发转码

**Comment by Hiold** [comment]
了解了

**Comment by 960269073** [comment]
了解了
