### ISSUE TITLE
请求重复了，导致接口duplicate vod signature

### ISSUE THREAD

**Issue by qianL93** [tencentyun/vod-js-sdk-v6#7]
https://github.com/tencentyun/vod-js-sdk-v6/blob/c3d2a967e740cefac580df3b91210ebd72d70924/src/uploader.ts#L329

我看`uploadToCos`方法有传入了`applyData`但是又调用了一次`applyUploadUGC`是为什么呢？

**Comment by alsotang** [comment]
getAuthorization 这个函数是让 cos 自己调用的。这里之所以写成这样，是为了在apply过期之后（比如连续上传了2个小时之类的），getAuthorization 总能拿到有效的apply信息。

**Comment by qianL93** [comment]
> getAuthorization 这个函数是让 cos 自己调用的。这里之所以写成这样，是为了在apply过期之后（比如连续上传了2个小时之类的），getAuthorization 总能拿到有效的apply信息。

明白了


还有个ts定义问题，`tcVod.upload`入参定义为`UploaderOptions `类型，根据定义`getSignature`是必填的，但从示例来看，`getSignature` 在 `new TcVod` 也传过一次额，`tcVod.upload`不用再传这个了。

**Comment by alsotang** [comment]
ts定义确实存在你说的这个问题，我待会儿修修

**Comment by alsotang** [comment]
ts的问题修了 

https://github.com/tencentyun/vod-js-sdk-v6/commit/d94a4730270f7c4359c187d02ee8075d6de92d2a?diff=split#diff-dad2556d08ca35ce53afaf92ab9e437dL24
