### ISSUE TITLE
是否支持传递 SourceContext

### ISSUE THREAD

**Issue by wangan** [tencentyun/vod-js-sdk-v6#8]
![image](https://user-images.githubusercontent.com/9428399/64141453-a6994b80-ce3a-11e9-83f8-edec41387a04.png)

[文档中心 > 云点播 > 开发指南 > 事件通知 > 视频上传完成](https://cloud.tencent.com/document/product/266/7830)

**Comment by alsotang** [comment]
我看了看文档，这个回调是你们服务端接收的。我这个是上传sdk控制不了那块。

**Comment by wangan** [comment]
回调是服务端接收的，但是这个SourceContext 是上传的SDK传的。主要用于给客户提供传递自定义内容。

![image](https://user-images.githubusercontent.com/9428399/64241217-d6794980-cf35-11e9-96e5-3747dd09e42d.png)

[文档](https://cloud.tencent.com/document/product/266/32320)

**Comment by alsotang** [comment]
好，我找相关同事问问看。

**Comment by alsotang** [comment]
同事回复：在签名里面携带就可以在回调中拿到。前端不需要填，签名带就可以了。

**Comment by wangan** [comment]
好的，多谢

**Comment by alsotang** [comment]
好的哈。有问题的话建议提工单，那样的话即时性和触达性都会比较好。
